"use client";

import { useEffect, useState } from "react";

const roles = ["system test tools", "sensor data pipelines", "re-simulation systems", "reliable embedded software"];
const experience = [
  {company:"Sprouts AI",role:"Software Engineer (C++ / Python / System Tools)",place:"Chicago, IL",date:"Mar 2025 — Present",bullets:["Designed, developed, and maintained C++ (14/17) system test tools and data processing pipelines on Linux handling large-scale sensor data across MDF4, CSV, and Parquet formats, reducing data validation cycle time by 35% through optimized multithreaded processing.","Architected object-oriented data logger modules recording sensor telemetry and bus data with time-synchronized capture, improving data integrity and traceability across test campaigns by 40%.","Built reprocessing (re-simulation) systems using ADTF-based workflows and ROS bag replay to run recorded camera, radar, and CAN data through perception and validation software, enabling automated regression testing and cutting defect detection time by 30%.","Designed database schemas and services (SQL and NoSQL) for test data management, metadata indexing, and efficient retrieval, delivering sub-second query performance for cross-functional teams.","Maintained CI/CD pipelines, wrote unit/integration tests, and conducted code reviews to ensure 92% test coverage; tracked requirements and defects in Codebeamer and trained tool users across a global 4-engineer team."]},
  {company:"Resilience Inc",role:"Software Engineer (C++ / Data Pipelines / Cloud)",place:"Chicago, IL",date:"Aug 2023 — Mar 2025",bullets:["Developed C++17 multithreaded data processing applications on Linux, designing thread-safe sensor data pipelines that improved data throughput and processing latency by 20%.","Built cloud-based infrastructure on AWS (S3, EC2, Lambda) with Python for data ingestion, storage, reprocessing, and retrieval of large-scale sensor datasets, enabling scalable re-simulation workflows.","Implemented image processing components using OpenCV for sensor data visualization and image quality checks, delivering automated visual inspection tooling that accelerated validation by 25%.","Developed and integrated ROS nodes, topics, services, and launch files for perception and sensor-fusion data workflows, debugging timing, synchronization, and coordinate-frame issues in SIL/HIL environments, cutting field-issue tickets by 18%.","Gathered, analyzed, and documented tool requirements in PTC Integrity with bidirectional traceability across requirements, code changes, and test results; collaborated with data collection, calibration, and software teams in Agile sprints."]},
  {company:"Tata Steel",role:"Software Engineer (C++ / Linux / Data Systems)",place:"",date:"Apr 2018 — Aug 2023",bullets:["Programmed C++ and Python application software on Linux for sensor data acquisition, integrating camera, ultrasonic, and radar sensor feeds into real-time operator display systems with continuous data logging.","Designed object-oriented, multithreaded data logger modules for machine diagnostics and sensor telemetry with time-synchronized capture, improving data capture reliability by 30%.","Built SQL (PostgreSQL, MySQL) database services for test data management and metadata indexing, enabling efficient retrieval and analysis of historical sensor datasets across production lines.","Led functional verification and validation aligned with ISO 26262 and Automotive SPICE practices, using unit/integration testing and root cause analysis with GDB and Valgrind, mentoring a 5-engineer team and lifting first-pass yield by 22%.","Maintained production data processing applications with Git source control and Jira defect tracking, delivering 99.99% uptime across machine lines."]}
];
const projects = [
  ["CME MDP 3.0 Multicast Feed Handler","Low-latency binary decoding, lock-free queues, and time-synchronized logging in C++.","C++ · Linux · Multithreading","https://github.com/devthedevil/CME-Multicast-Market-Data-Feed-Handler-C-",""],
  ["Real-time Stock Market Analysis Pipeline","A cloud pipeline for real-time ingestion, transformation, storage, and reprocessing.","Python · AWS · Data","https://github.com/devthedevil/Realtime-Stock-Market-Analysis",""],
  ["Experimental Operating System","An operating system built from the ground up to explore kernels and systems internals.","OS · Systems","https://github.com/devthedevil/EXPOS",""],
  ["Character Device Driver","Linux character device driver work focused on kernel-space interfaces and I/O.","C · Linux Kernel","https://github.com/devthedevil/Character-Device-Driver",""],
  ["LangChain: Chat with Search","An AI assistant combining conversational reasoning with search tools.","LangChain · AI","https://github.com/devthedevil/LangChain-Chat-with-Search",""],
  ["16-Bit RISC Processor","A hardware lab implementation exploring instruction execution and processor architecture.","RISC · Hardware","https://github.com/devthedevil/Hardware-lab",""],
  ["TradeSentinel","An interactive market intelligence experience for monitoring trade signals.","Markets · Web","https://github.com/devthedevil/tradesentinel","https://tradesentinel.vercel.app/"],
  ["AskMyStore","A LangGraph-orchestrated shopping intelligence application.","LangGraph · Agents","https://github.com/devthedevil/AskMyStore","https://ask-my-store.vercel.app/"],
  ["Pitch Perfect","An iOS application centered on audio recording and voice transformation.","iOS · Swift","https://github.com/devthedevil/Pitch_Perfect",""],
  ["STRANGERS","A responsive React application with a live web experience.","React · Web","https://github.com/devthedevil/Strangers","https://strangers-react.vercel.app/"],
  ["Hire Loop","A software project focused on improving the hiring workflow.","Product · Web","https://github.com/devthedevil/hireloop",""],
  ["AgentFlow","LangChain orchestration and agent workflows built with the OpenAI Agents SDK.","Agents · LangChain","https://github.com/devthedevil/openAI-Agent-SDK",""],
  ["Tic Tac Toe","A native Android implementation of the classic strategy game.","Android · Mobile","https://github.com/devthedevil/TicTacToe-Game",""],
  ["Model Context Protocol","Experiments and tooling around interoperable AI context and tool connections.","MCP · AI","https://github.com/devthedevil/MCP",""],
  ["Voting App","A multi-service voting application orchestrated with Kubernetes.","Kubernetes · DevOps","https://github.com/devthedevil/Kubernetes-K8",""],
  ["oxide-hv","A Rust-based systems project with an interactive technical showcase.","Rust · Systems","https://github.com/devthedevil/oxide-hv","https://oxide-hv.vercel.app/"]
];
function DynamicRole(){const [index,setIndex]=useState(0);useEffect(()=>{const t=setInterval(()=>setIndex(i=>(i+1)%roles.length),2300);return()=>clearInterval(t)},[]);return <span className="dynamic" key={roles[index]}>{roles[index]}</span>}
export default function Home(){return <main>
  <nav aria-label="Primary navigation"><a className="mark" href="#top"><i/>DK</a><div className="navlinks"><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#about">About</a></div><a className="navcta" href="mailto:devkumar.dklv@gmail.com">Let&apos;s talk <span>↗</span></a></nav>
  <section className="hero" id="top"><div className="eyebrow"><span className="pulse"/> Building dependable systems since 2018</div><h1>I turn complex data<br/>into <DynamicRole/>.</h1><p className="lede">Software engineer working where C++, Python, sensor data, and rigorous validation meet. I build the tools that help teams see clearly, test confidently, and ship reliably.</p><div className="heroActions"><a className="primary" href="#projects">Explore selected work <span>↓</span></a><a className="textLink" href="https://github.com/devthedevil" target="_blank" rel="noreferrer">GitHub ↗</a><a className="textLink" href="https://leetcode.com/u/dev_kumar_dklv/" target="_blank" rel="noreferrer">LeetCode ↗</a></div><div className="metrics"><div><strong>8+</strong><span>Years building<br/>production systems</span></div><div><strong>35%</strong><span>Faster data<br/>validation cycles</span></div><div><strong>99.99%</strong><span>Production<br/>uptime delivered</span></div><div><strong>92%</strong><span>Test coverage<br/>achieved</span></div></div></section>
  <section className="flowSection" id="about"><SectionIntro no="01" kicker="HOW I THINK" title="From raw signal to trusted decision." text="I care about the entire path—not just whether code runs, but whether data stays trustworthy, systems stay observable, and engineers can move with confidence."/><div className="flow">{[["01","CAPTURE","Camera · Radar · CAN","Time-synchronized collection"],["02","PROCESS","C++ · Python · OpenCV","Multithreaded transformation"],["03","REPLAY","ADTF · ROS · HIL/SIL","Repeatable re-simulation"],["04","VALIDATE","CI/CD · SQL · Cloud","Evidence-driven confidence"]].map((x,i)=><div className="flowNode" key={x[1]}><span>{x[0]}</span><div className="signal"><b/>{i<3&&<em/>}</div><h3>{x[1]}</h3><strong>{x[2]}</strong><p>{x[3]}</p></div>)}</div></section>
  <section className="experience" id="experience"><SectionIntro no="02" kicker="EXPERIENCE" title="Engineering with measurable impact." text="Eight years across system tooling, data platforms, cloud infrastructure, and validation—always close to the technical detail and the people using the result."/><div className="timeline">{experience.map((j,i)=><article className="job" key={j.company}><div className="jobMeta"><span className="jobIndex">0{i+1}</span><div><h3>{j.company}</h3><p>{j.role}</p>{j.place&&<small>{j.place}</small>}</div><time>{j.date}</time></div><ul>{j.bullets.map(b=><li key={b}>{b}</li>)}</ul></article>)}</div></section>
  <section className="projects" id="projects"><SectionIntro no="03" kicker="PROJECTS" title="Built to understand. Built to work." text="A living workshop spanning operating systems, market data, AI agents, cloud pipelines, hardware, mobile, and distributed infrastructure."/><div className="projectGrid">{projects.map((p,i)=><article className="project" key={p[0]}><div className="projectTop"><span>{String(i+1).padStart(2,"0")}</span><b>{p[2]}</b></div><h3>{p[0]}</h3><p>{p[1]}</p><div className="projectLinks"><a href={p[3]} target="_blank" rel="noreferrer">SourceCode ↗</a>{p[4]&&<a className="demo" href={p[4]} target="_blank" rel="noreferrer">Technical Demo ↗</a>}</div></article>)}</div></section>
  <section className="publication"><SectionIntro no="04" kicker="RESEARCH + LEARNING" title="Curiosity with a paper trail." text="Formal research, deep systems work, and continuous practice all feed the same habit: understanding how things behave, then making them better."/><div className="paper"><div><span>IEEE · 2021</span><h3>A Comparative Study of Movie Recommendation Systems with Improved Error Function</h3><p>Published research exploring recommendation approaches and an improved error function.</p></div><div className="paperLinks"><a href="https://ieeexplore.ieee.org/document/10094480" target="_blank" rel="noreferrer">Read paper ↗</a><a href="https://github.com/devthedevil/Comparative-Study-of-Movie-Recommendation-System/blob/main/Netflix_Movie.ipynb" target="_blank" rel="noreferrer">SourceCode ↗</a><a href="https://drive.google.com/file/d/1rayr6Cht6quyLUJOXWOAcBi_rxQp2Ol0/view" target="_blank" rel="noreferrer">Certificate ↗</a></div></div><div className="education"><div><span>01</span><p><b>Illinois Institute of Technology</b><br/>M.S., Computer Science</p></div><div><span>02</span><p><b>National Institute of Technology Calicut</b><br/>B.S., Computer Science</p></div></div></section>
  <section className="contact"><p className="kicker">LET&apos;S BUILD SOMETHING RELIABLE</p><h2>Complex system?<br/><span>I&apos;m listening.</span></h2><a href="mailto:devkumar.dklv@gmail.com">devkumar.dklv@gmail.com <b>↗</b></a><div className="socials"><a href="https://github.com/devthedevil" target="_blank" rel="noreferrer">GitHub</a><a href="https://leetcode.com/u/dev_kumar_dklv/" target="_blank" rel="noreferrer">LeetCode</a></div></section>
</main>}
function SectionIntro({no,kicker,title,text}:{no:string;kicker:string;title:string;text:string}){return <div className="sectionIntro"><span className="sectionNo">{no}</span><div><p className="kicker">{kicker}</p><h2>{title}</h2></div><p>{text}</p></div>}
